apiVersion: v1
kind: Service
metadata:
  name: systems-numbers-service
spec:
  selector:
    app: systems-numbers  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
