---
- name: Setup and Run systems number App in Docker Container
  hosts: Systems Number  
  become: true
  roles:
    - docker 
  tasks:
    - name: Pull the Docker image from DockerHub
      docker_image:
        name: a7medd3lii/systems-number
        tag: v1.1
        source: pull
s
    - name: Run Docker container
      docker_container:
        name: systems-number
        image: a7medd3lii/systems-number:v1.1
        state: started
        restart_policy: always
        ports:
          - "80:5000"